### ISSUE TITLE
Repositories with Spring Boot 2.0

### ISSUE THREAD

**Issue by mrjavascript** [wwadge/hbnpojogen#15]
The repositories that are generated, e.g. ApplicationUserRepository, look like the following:

`public interface ApplicationUserRepository extends JpaRepository<ApplicationUser, Long>, QueryDslPredicateExecutor<ApplicationUser> {`

In Spring Boot 2, the Query DSL predicate executor changes to the following:

`import org.springframework.data.querydsl.QuerydslPredicateExecutor;
`
Changing the extends to use the lowercase convention fixes the issue.

**Comment by wwadge** [comment]
Try v1.5.9
