### ISSUE TITLE
[enhancement] Create a Release package

### ISSUE THREAD

**Issue by LuccaPrado** [wwadge/hbnpojogen#16]
Hi, I found this project after some research about creating pojo from database and beign upset after noticing that the easiest way is using eclipse with one plugin, but, for who is just looking for an easy way to do its job would be really nice to just download an .jar from release and start using! I also think that if there's one release .jar the popularity of your project would increase a lot

**Comment by wwadge** [comment]
The intended use of this tool is via maven/gradle integration as part of the build process. The binaries can be found here: https://mvnrepository.com/artifact/com.github.wwadge/hbnpojogen-core/1.5.11
